package com.itau.abrecontacase.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "itau-abreconta-case")
public class UsuarioEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String uid;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String nome;

    @DynamoDBAttribute
    private String cpf;

    @DynamoDBAttribute
    private String telefone;

    @DynamoDBAttribute
    private String endereco;

    @DynamoDBAttribute
    private String complemento;

    @DynamoDBAttribute
    private String cidade;

    @DynamoDBAttribute
    private String estado;

    @DynamoDBAttribute
    private String pais;

    @DynamoDBAttribute
    private String cep;

}
